[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
opacity = 0.8

[window.padding]
x = 5
y = 2

[font]
size = 19.0


[font.bold]
family = "FiraCode Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
